language: android

sudo: false

jdk:
  - oraclejdk8

android:
  components:
    - build-tools-24.0.1
    - android-24
    - extra-android-m2repository

before_script:
  - cp signing.properties.travis signing.properties
